#=====================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/download-artifact@v1
      with:
        name: Build G-DOCK

    - run: cat Build G-DOCK
