#=====================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK 
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download artifact
      uses: rexyu/action-download-artifact@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: a.yml
        commit: ${{github.event.pull_request.head.sha}}
        name: G-DOCK
        path: ./
