#=====================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK 
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - run: mkdir bin
      
    - name: Download artifact
      uses: rexyu/action-download-artifact@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: a.yml
        commit: '9925657286c48228a58a9e98173d61a2f512b7fe'
        name: G-DOCK
        path: ./bin

    - name: Tar bin
      run : |
        tar -zcvf bin.tar.gz ./lede   
    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "bin.tar.gz"
        draft: true
