#=================================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK
#=================================================

name: Build G-DOCK

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install git  unzip zlib1g-dev lib32gcc1 git-core gcc-multilib p7zip p7zip-full  libssl-dev texinfo
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Cache Lede
      id: cache-lede
      uses: actions/cache@v1
      with:
        path: lede
        key: ${{ runner.os }}-lede
      
    - name: clone lede
      if: steps.cache-lede.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/coolsnowwolf/lede lede
         
    - name: pull lede
      if: steps.cache-lede.outputs.cache-hit == 'true'
      run: |
        cd lede && git pull
    - name: ZIP
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./dir.zip ./lede
    
    - name: Upload asset to release
      uses: actions-github/upload-to-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: './dir.zip'
        type: 'application/octet-stream'
