#=================================================
# https://github.com/rexyu/Actions
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT 
# Author: DevDev
# Blog: https://openwrt.devdev.cn
#=================================================

name: Build MAC K2 

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '**/build-macos-k2.yml'
      - 'k2-base.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  DL_URL: https://github.com/rexyu/dl/
  REPO_BRANCH: master
  DL_BRANCH: master
  CONFIG_FILE: k2-base.config
  DIY_SH: diy.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
  BUILD_NAME: k2

jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep wget quilt xz
        echo 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        hdiutil create -size 50g -type SPARSE -fs "Case-sensitive HFS+" -volname OpenWrt OpenWrt.sparseimage
        hdiutil attach OpenWrt.sparseimage
        
    - name: Checkout
      uses: actions/checkout@master
   
    - name: Clone source code
      run: |
        cd /Volumes/OpenWrt/
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
      
    - name: Clone download
      run: |
        cd /Volumes/OpenWrt/
        git clone --depth 1 $DL_URL -b $DL_BRANCH dl
        cd openwrt && ln -s ../dl dl 
        
