#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX      
# Blog: https://p3terx.com
#=================================================

name: Upload Bin

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - '**/upload-release.yml'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
   
    - name: Download artifact
      uses: dawidd6/action-download-artifact@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build-gdock.yml
        commit: ${{github.event.pull_request.head.sha}}
        name: artifact_name
        path: extract_here
   
   
    - name: Upload to release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "G-DOCK.zip"
        draft: true
